
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OnlineStore.Model.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Customer
{

    public long Id { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public Nullable<int> OrderId { get; set; }

    public string Email { get; set; }



    public virtual ecom_Orders ecom_Orders { get; set; }

}

}
